#! /usr/bin/env python

###############################################################################
#
# Package:  kuon
#
# File: kuon_panel
#
## \file 
##
## $LastChangedDate: 2012-12-06 16:33:18 -0700 (Thu, 06 Dec 2012) $
## $Rev: 330 $
##
## \brief Graphical panel to interface with the kuon_control node.
##
## \author Daniel Packard (daniel@roadnarrows.com)
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2013.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

import sys
import os
import time
import math
import getopt

from Tkinter import *
from Tkconstants import *
from tkFileDialog import *
import tkFont

from PIL import Image, ImageTk

import webbrowser
import xml.parsers.expat as expat

import roslib; roslib.load_manifest('kuon_control')
import rospy

from industrial_msgs.msg import RobotMode
from industrial_msgs.msg import TriState

from kuon_control.msg import BrakeCmd           # publish
from kuon_control.msg import KuonState          # subscribe (TBD)
from kuon_control.msg import KuonStatus         # subscribe
from kuon_control.msg import SlewCmd            # publish
from kuon_control.msg import SpeedCmd           # publish
from kuon_control.msg import Version            # service
from kuon_control.srv import IncrementGovernor  # service (TBD)
from kuon_control.srv import EStop              # service
from kuon_control.srv import ResetEStop         # service
from kuon_control.srv import QueryVersion       # service (TBD)

import actionlib
import kuon_control.msg
import trajectory_msgs.msg


# ------------------------------------------------------------------------------
# Globals
# ------------------------------------------------------------------------------

## \brief Application version. Update as needed. 
appVersion = '1.0.0'

## \brief Image search paths.
imagePath = [
  "/prj/pkg/Kuon/share/images",
  "/usr/local/share/Kuon/images",
  "/prj/pkg/appkit/share/images",
  "/usr/local/share/appkit/images"
]

## \brief User's home directory.
home = os.path.expanduser("~")

## \brief Kuon user-specific configuration directory (in home directory).
kuonUserDirName = ".kuon"

## \brief kuon_panel application configuration file name.
configFileName = "kuon_panel.xml"

## \brief Configuration default.
configDft = \
{
}

## \brief Alarm strings.
alarmStrings = {
}

## \brief Common foreground colors.
fgColors = {
  'normal':   'black',
  'ok':       '#008800',
  'focus':    '#0000aa',
  'warning':  '#aa6600',
  'error':    '#cc0000'
}


# ------------------------------------------------------------------------------
# Utilities
# ------------------------------------------------------------------------------

#
## \brief Load icon image from file name.
##
## \param filename    Icon file name.
##
## \return Returns icon widget on success, None on failure.
#
def loadIcon(filename):
  # no file name
  if filename is None or len(filename) == 0:
    return None;
  # absolute file name
  if filename[0] == os.path.sep:
    try:
      return ImageTk.PhotoImage(Image.open(filename))
    except IOError:
      return None
  # relative file name - search path for file
  for path in imagePath:
    fqname = path + os.path.sep + filename
    try:
      return ImageTk.PhotoImage(Image.open(fqname))
    except IOError:
      continue
  return None

#
## Round to nearest 100th.
#
def round100th(x):
  return math.floor((x + 0.005) * 100.0) / 100.0

#
## Round to nearest 10th.
#
def round10th(x):
  return math.floor((x + 0.05) * 10.0) / 10.0

#
## Degrees to radians.
#
def degToRad(deg):
  return deg / 180.0 * math.pi

#
## Radians to degrees.
#
def radToDeg(rad):
  return rad / math.pi * 180.0


# ------------------------------------------------------------------------------
# Class configXml
# ------------------------------------------------------------------------------

##
## \brief Application kuon_panel configuration xml class.
##
class configXml():
  def __init__(self):
    self.m_inRootElem   = False
    self.m_inMainElem   = False
    self.m_curCfgElem   = None
    self.m_curData      = ""
    self.m_cfgElems     = configDft.keys()
    self.m_config       = None

  def parse(self, pathname):
    self.m_config = configDft
    try:
      fp = open(pathname, 'r')
    except IOError, err:
      return self.m_config
    parser = expat.ParserCreate()
    parser.returns_unicode      = False
    parser.StartElementHandler  = self.onElemStart
    parser.CharacterDataHandler = self.onElemData
    parser.EndElementHandler    = self.onElemEnd
    try:
      parser.ParseFile(fp)
    except expat.ExpatError as e:
      print "%s: %s" % (pathname, expat.ErrorString(e.code))
    fp.close()
    return self.m_config

  def save(self, pathname, config):
    try:
      fp = open(pathname, 'w')
    except IOError, err:
      print "%s: %s." % (pathname, err)
      return
    fp.write("""\
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://roadnarrows.com/xml/Kuon/1.0/kuon.xsl"?>

<!-- RoadNarrows Kuon Top-Level Configuration -->
<kuon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://roadnarrows.com/xml/Kuon/1.0/kuon.xsd">

  <!-- kuon_panel configuration -->
  <kuon_panel>
""")

    for key in self.m_cfgElems:
      fp.write("    <%s>%d</%s>\n" % (key, config[key], key))

    fp.write("""\
  </kuon_panel>

</kuon>
""")

    fp.close()

  def onElemStart(self, elem, attrs):
    #print "start-of-element", "<%s> attrs=%s" % (elem, repr(attrs))
    if elem == 'kuon':
      self.m_inRootElem = True
    elif elem == 'kuon_panel':
      if self.m_inRootElem:
        self.m_inMainElem = True
      else:
        self.m_inMainElem = False
    elif elem in self.m_cfgElems:
      if self.m_inMainElem:
        self.m_curCfgElem = elem
      else:
        self.m_inMainElem = None
    self.m_curData  = ""

  def onElemData(self, data):
    #print "char-data", repr(data)
    self.m_curData += data

  def onElemEnd(self, elem):
    #print "end-of-element", "<\%s>" % (elem)
    if self.m_curCfgElem:
      self.cvtToBool(self.m_curCfgElem, self.m_curData.strip())
    if elem == 'kuon_panel':
      self.m_inMainElem = False
    elif elem == 'kuon':
      self.m_inRootElem = False
      self.m_inMainElem = False
    m_curCfgElem = None
    self.m_curData  = ""

  def cvtToBool(self, elem, data):
    if data.lower() == 'true':
      self.m_config[elem] = True
    elif data.lower() == 'false':
      self.m_config[elem] = False
    else:
      try:
        i = int(data)
      except ValueError:
        return
      if i:
        self.m_config[elem] = True
      else:
        self.m_config[elem] = False


# ------------------------------------------------------------------------------
# Class configDlg
# ------------------------------------------------------------------------------

"""
class configDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title("kuon_panel configuration")

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnCancel.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    if kw.has_key('config'):
      self.m_config = kw['config']
      del kw['config']
    else:
      self.m_config = configDft;
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    # top heading
    w = Label(frame)
    helv = tkFont.Font(family="Helvetica",size=24,weight="bold")
    w['font']   = helv
    w['text']   = 'Configuration'
    w['anchor'] = CENTER
    w.grid(row=0, column=0, sticky=E+W)

    row = 1

    # warn on calibrate check button
    self.m_varWarnCalib = IntVar()
    self.m_varWarnCalib.set(self.m_config['warn_on_calib'])
    w = Checkbutton(frame, text="Show warning dialog before calibrating arm.",
        variable=self.m_varWarnCalib)
    w.grid(row=row, column=0, padx=5, sticky=W)

    row += 1

    # force recalibration on all joints check button
    self.m_varForceRecalib = IntVar()
    self.m_varForceRecalib.set(self.m_config['force_recalib'])
    w = Checkbutton(frame,
        text="Force (re)calibration for all joints on calibrate action.",
        variable=self.m_varForceRecalib)
    w.grid(row=row, column=0, padx=20, sticky=W)

    row += 1

    # warn on release check button
    self.m_varWarnRelease = IntVar()
    self.m_varWarnRelease.set(self.m_config['warn_on_release'])
    w = Checkbutton(frame, text="Show warning dialog before releasing arm.",
        variable=self.m_varWarnRelease)
    w.grid(row=row, column=0, padx=5, sticky=W)

    row += 1

    wframe = Frame(frame)
    wframe.grid(row=row, column=0)

    # cancel button
    w = Button(wframe, width=10, text='Cancel', command=self.close)
    w.grid(row=0, column=0, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnCancel = w

    # save button
    w = Button(wframe, width=10, text='Save', command=self.ok)
    w.grid(row=0, column=1, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnOk = w

  #
  ## \brief Destroy window callback.
  #
  def ok(self):
    if self.m_varWarnCalib.get():
      self.m_config['warn_on_calib'] = True
    else:
      self.m_config['warn_on_calib'] = False
    if self.m_varForceRecalib.get():
      self.m_config['force_recalib'] = True
    else:
      self.m_config['force_recalib'] = False
    if self.m_varWarnRelease.get():
      self.m_config['warn_on_release'] = True
    else:
      self.m_config['warn_on_release'] = False

    dirname = home + os.path.sep + kuonUserDirName
    if not os.path.isdir(dirname):
      try:
        os.mkdir(dirname, 0755)
      except OSError, err:
        print "%s: %s" % (dirname, err)
        return
    filename = dirname + os.path.sep + configFileName
    xml = configXml()
    xml.save(filename, self.m_config)
    self.close()

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()
"""


# ------------------------------------------------------------------------------
# Class warnDlg
# ------------------------------------------------------------------------------

class warnDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title(self.m_title)

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnCancel.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    self.m_icons          = {}    # must keep loaded icons referenced
    if kw.has_key('title'):
      self.m_title = kw['title']
      del kw['title']
    else:
      self.m_title = "Warning"
    if kw.has_key('image'):
      self.m_icons['image'] = loadIcon(kw['image'])
      del kw['image']
    else:
      self.m_icons['image'] = None
    if kw.has_key('msg'):
      self.m_msg = kw['msg']
      del kw['msg']
    else:
      self.m_msg = "Warn what???"
    self.m_result = False
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    # warning image 
    w = Label(frame)
    if self.m_icons['image'] is not None:
      w = Label(frame)
      w['image']  = self.m_icons['image']
    w['anchor'] = CENTER
    w.grid(row=0, column=0, rowspan=2, sticky=W+N+S)

    # top heading
    w = Label(frame)
    helv = tkFont.Font(family="Helvetica",size=24,weight="bold")
    w['font']   = helv
    w['text']   = 'Warning'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    row = 1

    # warning message
    w = Label(frame)
    w['text']   = self.m_msg
    w['anchor'] = W
    w['justify'] = LEFT
    w.grid(row=row, column=1, padx=5, sticky=E+W)

    row += 1

    wframe = Frame(frame)
    wframe.grid(row=row, column=1)

    # cancel button
    w = Button(wframe, width=10, text='Cancel', command=self.close)
    w.grid(row=0, column=0, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnCancel = w

    # ok button
    w = Button(wframe, width=10, text='Continue', command=self.ok)
    w.grid(row=0, column=1, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnContinue = w

  #
  ## \brief Destroy window callback.
  #
  def ok(self):
    self.m_result = True
    self.close()

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()


# ------------------------------------------------------------------------------
# Class moveDlg
# ------------------------------------------------------------------------------

class moveDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title(self.m_title)

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnCancel.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    self.m_icons          = {}    # must keep loaded icons referenced
    if kw.has_key('title'):
      self.m_title = kw['title']
      del kw['title']
    else:
      self.m_title = "Move Arm To..."
    if kw.has_key('image'):
      self.m_icons['image'] = loadIcon(kw['image'])
      del kw['image']
    else:
      self.m_icons['image'] = None
    self.m_result = False
    self.m_trajectory = kw['trajectory']
    self.m_vals = { }
    del kw['trajectory']
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    # move image 
    w = Label(frame)
    if self.m_icons['image'] is not None:
      w = Label(frame)
      w['image']  = self.m_icons['image']
    w['anchor'] = CENTER
    w.grid(row=0, column=0, rowspan=2, sticky=W+N+S)

    # top heading
    w = Label(frame)
    helv = tkFont.Font(family="Helvetica",size=12,weight="bold")
    w['font']   = helv
    w['text']   = 'Specify Trajectory'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    width = 12
    padx  = 2
    pady  = 3
    row   = 1

    wframe = Frame(frame)
    wframe.grid(row=row, column=1)

    #
    # Trajectory Table
    #
    row   = 0

    # left column of labels
    for text in [' ', 'Position(deg):', 'Velocity(%max):', 'Group Velocity:']:
      w = Label(wframe, width=width, padx=padx, pady=pady, anchor=W, text=text)
      w.grid(row=row, column=0, sticky=W+S)
      row += 1

    col         = 1
    trajPoint   = self.m_trajectory.points[0]
    startGroupV = 0.0

    i = 0
    for name in self.m_trajectory.joint_names:
      # joint label
      row = 0
      w = Label(wframe, width=width, padx=padx, pady=pady, anchor=W, text=name)
      w.grid(row=row, column=col, sticky=W)
      self.m_vals[name] = { }

      # joint position
      row += 1
      var = DoubleVar()
      var.set(round10th(radToDeg(trajPoint.positions[i])))
      w = Spinbox(wframe, justify=RIGHT, textvar=var,
                        increment=0.1, from_=-720.0, to=720.0,
                        fg=fgColors['normal'])
      w['width'] = 7
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_vals[name]['position'] = d
    
      # joint velocity
      row += 1
      var = DoubleVar()
      var.set(round10th(trajPoint.velocities[i]))
      startGroupV = var.get()
      w = Spinbox(wframe, justify=RIGHT, textvar=var,
                        increment=0.1, from_=0.0, to=100.0,
                        fg=fgColors['normal'])
      w['width'] = 7
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_vals[name]['velocity'] = d
    
      col += 1
      i += 1

    if i > 0:
      self.update_idletasks()
      name = self.m_trajectory.joint_names[0]
      x0 = self.m_vals[name]['position']['w'].winfo_rootx()
      name = self.m_trajectory.joint_names[i-1]
      x1 = self.m_vals[name]['position']['w'].winfo_rootx() + \
           self.m_vals[name]['position']['w'].winfo_width()
      length = x1 - x0
    else:
      length = 100

    # delta group velocity
    self.m_varGroupVel = DoubleVar()
    self.m_varGroupVel.set(round10th(startGroupV))
    w = Scale(wframe, variable=self.m_varGroupVel,
                        from_=0.0, to=100.0, resolution=1.0,
                        orient=HORIZONTAL, command=self.setGroupV)
    w['width']  = 10
    w['length'] = length
    w.grid(row=3, column=1, columnspan=i, padx=1, pady=0, sticky=W)

    #
    # Dialog Buttons
    #
    row = 2

    wframe = Frame(frame)
    wframe.grid(row=row, column=1)

    # cancel button
    w = Button(wframe, width=10, text='Cancel', command=self.close)
    w.grid(row=0, column=0, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnCancel = w

    # ok button
    w = Button(wframe, width=10, text='Move', command=self.ok)
    w.grid(row=0, column=1, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnContinue = w

  #
  ## \brief Delta velocity callback
  #
  def setGroupV(self, v):
    vel = self.m_varGroupVel.get()
    for name in self.m_vals:
      self.m_vals[name]['velocity']['var'].set(vel)

  #
  ## \brief Destroy window callback.
  #
  def ok(self):
    i = 0
    trajPoint = self.m_trajectory.points[0]
    for name in self.m_trajectory.joint_names:
      pos = self.m_vals[name]['position']['var'].get()
      vel = self.m_vals[name]['velocity']['var'].get()
      if vel < 0.0:
        vel = 0.0
      elif vel > 100.0:
        vel = 100.0
      trajPoint.positions[i]  = degToRad(pos)
      trajPoint.velocities[i] = vel
      i += 1
    self.m_result = True
    self.close()

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()


# ------------------------------------------------------------------------------
# Class aboutDlg
# ------------------------------------------------------------------------------

class aboutDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title("About Kuon")

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnOk.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # start with ok button focused
    #self.m_bttnOk.focus_set()

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    self.m_icons          = {}    # must keep loaded icons referenced
    self.m_prodName       = "Kuon"
    self.m_hwVer          = "0.9.1"
    self.m_prodId         = "RN.Kuon"
    self.m_prodBrief      = "Kuon Outdoor Mobile Robot"
    self.m_rnUrl          = "http://www.roadnarrows.com/Kuon"
    self.m_rnEmail        = "support@roadnarrows.com"
    self.m_rnTel          = "+1.800.275.9568"
    if kw.has_key('info'):
      info = kw['info']
      if info is not None:
        self.m_hwVer = info.version_string
        self.m_prodName = info.product_name
        self.m_prodId = info.product_id
        self.m_prodBrief = info.desc
      del kw['info']
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    self.m_icons['kuon_logo'] = loadIcon("KuonLogo.png")

    # top heading
    w = Label(frame)
    times32 = tkFont.Font(family="Times",size=32,weight="bold")
    w['font']   = times32
    w['text']   = 'Kuon'
    w['anchor'] = W
    w.grid(row=0, column=1, columnspan=2, sticky=E+W)

    lwidth = 10
    rwidth = 26

    row = 1

    # product brief
    w = Label(frame)
    w['text']   = self.m_prodBrief
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=1, columnspan=2, padx=2, sticky=W)

    row += 1

    # product name
    w = Label(frame)
    w['text']   = 'Product:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Label(frame)
    w['text']   = self.m_prodName
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=2, padx=2, sticky=W)

    row += 1

    # product id
    w = Label(frame)
    w['text']   = 'Product Id:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Label(frame)
    w['text']   = self.m_prodId
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=2, padx=2, sticky=W)

    row += 1

    # hw version
    w = Label(frame)
    w['text']   = 'HW Version:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Label(frame)
    w['text']   = self.m_hwVer
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=2, padx=2, sticky=W)

    row += 1

    # app version
    w = Label(frame)
    w['text']   = 'App Version:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Label(frame)
    w['text']   = appVersion
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=2, padx=2, sticky=W)

    row += 1

    # url
    w = Label(frame)
    w['text']   = 'URL:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Button(frame)
    w['text']   = 'www.roadnarrows.com/Kuon'
    w['fg']   = '#aa0000'
    w['activeforeground']   = '#cc0033'
    w['activebackground']   = w['bg']
    w['cursor'] = 'hand1'
    w['anchor'] = W
    w['justify'] = LEFT
    w['relief']   = 'flat'
    w['borderwidth']   = 0
    w['padx']   = 0
    w['pady']   = 0
    w['width']  = rwidth
    w['command']  = lambda aurl=self.m_rnUrl:webbrowser.open_new(self.m_rnUrl)
    w.grid(row=row, column=2, ipadx=0, ipady=0, padx=2, pady=0, sticky=W)

    row += 1

    # support email
    w = Label(frame)
    w['text']   = 'Email:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Label(frame)
    w['text']   = self.m_rnEmail
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=2, padx=2, sticky=W)

    row += 1

    # telephone
    w = Label(frame)
    w['text']   = 'Tel:'
    w['anchor'] = W
    w['width'] = lwidth
    w.grid(row=row, column=1, padx=2, sticky=W)

    w = Label(frame)
    w['text']   = self.m_rnTel
    w['anchor'] = W
    w['width']  = rwidth
    w.grid(row=row, column=2, padx=2, sticky=W)

    row += 1

    # product logo
    w = Label(frame)
    if self.m_icons['kuon_logo'] is not None:
      w['image']  = self.m_icons['kuon_logo']
    w['anchor'] = CENTER
    w.grid(row=0, column=0, rowspan=row, sticky=W+N+S)

    # who
    w = Label(frame)
    w['text']   = """
Kuon is designed and developed by RoadNarrows, a robotics and intelligent systems
company base in Colorado USA. We are dedictated to supporting open software and
hardware interfaces to foster a global community of users and developers."""
    w['justify'] = LEFT
    w['anchor'] = W
    w.grid(row=row, column=0, columnspan=3, padx=5, sticky=W)

    row += 1

    # ok button
    w = Button(frame, width=10, text='OK', command=self.close)
    w.grid(row=row, column=0, columnspan=3, pady=5)
    w['anchor']  = CENTER
    self.m_bttnOk = w

    row += 1

    # legal
    w = Label(frame)
    helv8 = tkFont.Font(family="Helvetica",size=8)
    w['font']   = helv8
    w['anchor'] = W
    w['fg']     = '#666666'
    w['text']   = "Kuon and the Kuon logos are the trademarks of " \
                  "RoadNarrows LLC"
    w.grid(row=row, column=0, columnspan=3, pady=5)

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()


# ------------------------------------------------------------------------------
# Class window
# ------------------------------------------------------------------------------

##
## \brief Window class supporting application.
##
class window(Frame):
  #
  ## \brief Constructor.
  ##
  ## \param master  Window parent master widget.
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # intialize window data
    kw = self.initData(kw)

    # publish speed command
    self.m_pub_speed_cmd = rospy.Publisher("kuon_control/speed_cmd", SpeedCmd)

    Frame.__init__(self, master=master, cnf=cnf, **kw)
    self.master.title("Kuon Control Panel")
    self.grid(row=0, column=0, padx=5, pady=5)

    # craete and show widgets
    self.createWidgets()

  #
  ## \brief Initialize class state data.
  ##
  ## Any keywords for this application specific window that are not supported 
  ## by the Frame Tkinter class must be removed.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  #
  def initData(self, kw):
    self.m_bHasJointPanel = False # joint state panel [not] created 
                                  # application configuration
    self.m_config         = configDft
    self.m_icons          = {}    # must keep loaded icons referenced
    self.m_wBttn          = {}    # button widgets
    self.m_keysFewMoves   = []    # gui button keys depending on calibration
    self.m_keysNoMoves    = []    # gui button keys depending on robot mode
    self.m_robotStatus    = {}    # robot status widgets, variables, and values
    self.m_robotJoint     = {}    # robot joint state widgets, variables, etc.
    self.m_robotServo     = {}    # master servo to joint name map
                                  # calibration state
    self.m_calibState     = \
      {
        'calibrating':  False,    # [not] calibrating
        'ac':           None,     # calibration action client
        'id':           0         # after id
      }

    if kw.has_key('config'):
      self.m_config = kw['config']
      del kw['config']
    if kw.has_key('pub_joint_move_cb'):
      self.cbMoveRobot = kw['pub_joint_move_cb']
      del kw['pub_joint_move_cb']

    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    self.createHeading()
    self.createLeftButtons()
    self.createCenterPanel()
    self.createRightButtons()
    self.createStatusBar()
    self.updateButtonState(self.m_keysFewMoves, 'disabled')

  #
  ## \brief Create top gui heading.
  #
  def createHeading(self):
    # rn logo
    w = Label(self)
    self.m_icons['rn_logo'] = loadIcon("RNLogo48.png");
    if self.m_icons['rn_logo']:
      w['image'] = self.m_icons['rn_logo']
    else:
      w['text'] = 'rn'
      w['anchor'] = W
      w['width'] = 5
    w.grid(row=0, column=0, sticky=W)
    
    # top heading
    w = Label(self)
    w['font']   = ('Helvetica', 16)
    w['text']   = 'Kuon Control Panel'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    # kuon logo
    w = Label(self)
    self.m_icons['kuon_logo'] = loadIcon("icons/icon_kuon_logo.png");
    if self.m_icons['kuon_logo']:
      w['image'] = self.m_icons['kuon_logo']
      w['anchor'] = E
    else:
      w['text'] = 'kuon'
      w['anchor'] = E
      w['width'] = 5
    w.grid(row=0, column=2, sticky=E)
    
  #
  ## \brief Create gui left hand side buttons.
  #
  def createLeftButtons(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=0, padx=1, pady=3, sticky=N+W+E)

    # move foward
    w = self.createButton(wframe, "Forward", "icons/icon_kuon_forward.png",
                            self.kuonMoveForward)
    w.grid(row=1, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('forward')

    # move backward
    w = self.createButton(wframe, "Back", "icons/icon_kuon_back.png",
                            self.kuonMoveBackward)
    w.grid(row=2, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('back')

    # spin left
    w = self.createButton(wframe, "Spin\nLeft", "icons/icon_kuon_spin_left.png",
                            self.kuonSpinLeft)
    w.grid(row=3, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('spin_left')

    # spin right
    w = self.createButton(wframe, "Spin\nRight",
                            "icons/icon_kuon_spin_right.png",
                            self.kuonSpinRight)
    w.grid(row=4, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('spin_right')

    # stop 
    w = self.createButton(wframe, "Stop",
                                  "icons/icon_kuon_brake.png",
                                  self.kuonStop)
    w.grid(row=5, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('stop')

    ## specify move
    #w = self.createButton(wframe, "Specify\nMove",
    #                              "icons/icon_kuon_in_motion.png",
    #                              self.specifyMove)
    #w.grid(row=6, column=0, sticky=N+E+W)
    #self.m_keysNoMoves.append('specify_move')

  #
  ## \brief Create robot status and joint state center panel.
  #
  def createCenterPanel(self):
    self.m_wPanelFrame = Frame(self)
    self.m_wPanelFrame['borderwidth'] = 2
    self.m_wPanelFrame['relief'] = 'ridge'
    self.m_wPanelFrame.grid(row=1, column=1, padx=1, pady=3, sticky=N+W+E)

    self.createRobotStatusPanel(self.m_wPanelFrame)
    self.createWheelStatePanelHdr(self.m_wPanelFrame)

  #
  ## \brief Create robot status upper center panel.
  ##
  ## \param parent  Parent widget
  #
  def createRobotStatusPanel(self, parent):
    wframe = Frame(parent)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=0, column=0, padx=1, pady=3, sticky=N+W+E)

    # heading
    w = Label(wframe)
    w['font'] =('Helvetica', 12)
    w['text'] = 'Status'
    w['justify'] = CENTER
    w.grid(row=0, column=0, columnspan=9, sticky=E+W)

    width = 14
    row   = 1
    col   = 0

    # robot mode status
    var = StringVar()
    var.set("Manual mode")
    w = Entry(wframe)
    w['borderwidth'] = 2
    w['relief']   = 'flat'
    w['width']    = width
    w['textvar']  = var
    w['fg']       = fgColors['normal']
    w['state']    = 'readonly'
    w.grid(row=row, column=col, padx=0, pady=0, sticky=W)
    d = {'val': False, 'var': var, 'w': w}
    self.m_robotStatus['mode'] = d

    col += 1

    # robot motors status
    var = StringVar()
    var.set("Motors powered")
    w = Entry(wframe)
    w['borderwidth'] = 2
    w['relief']   = 'flat'
    w['width']    = width
    w['textvar']  = var
    w['fg']       = fgColors['normal']
    w['state']    = 'readonly'
    w.grid(row=row, column=col, padx=0, pady=0, sticky=W)
    d = {'val': True, 'var': var, 'w': w}
    self.m_robotStatus['motors'] = d

    col += 1

    self.m_icons['led_dark']  = loadIcon("icons/icon_led_dark_16.png")
    self.m_icons['led_green'] = loadIcon("icons/icon_led_green_16.png")
    self.m_icons['led_red']   = loadIcon("icons/icon_led_red_16.png")

    width = 10

    # moving status
    w = Label(wframe)
    w['text']     = 'Moving'
    w['width']    = width
    w['justify']  = RIGHT
    w['anchor']   = E
    w['relief']   = 'flat'
    w.grid(row=row, column=col, sticky=E)
    d = {'val': None, 'var': None, 'w': w}
    self.m_robotStatus['moving_label'] = d

    col += 1

    # moving icon
    w = Label(wframe)
    w['image'] = self.m_icons['led_dark']
    w['justify'] = LEFT
    w.grid(row=row, column=col, sticky=W)
    d = {'val': False, 'var': None, 'w': w}
    self.m_robotStatus['moving_led'] = d

    col += 1

    # robot alarms status
    w = Label(wframe)
    w['text']     = 'Alarms'
    w['width']    = width
    w['justify']  = RIGHT
    w['anchor']   = E
    w['relief']   = 'flat'
    w.grid(row=row, column=col, sticky=E)
    d = {'val': None, 'var': None, 'w': w}
    self.m_robotStatus['alarms_label'] = d

    col += 1

    # alarms icon
    w = Label(wframe)
    w['image'] = self.m_icons['led_dark']
    w['justify'] = LEFT
    w.grid(row=row, column=col, sticky=W)
    d = {'val': False, 'var': None, 'w': w}
    self.m_robotStatus['alarms_led'] = d

    col += 1

    # robot estop status
    w = Label(wframe)
    w['text']     = 'EStop'
    w['width']    = width
    w['justify']  = RIGHT
    w['anchor']   = E
    w['relief']   = 'flat'
    w.grid(row=row, column=col, sticky=E)
    d = {'val': None, 'var': None, 'w': w}
    self.m_robotStatus['estop_label'] = d

    col += 1

    # estop icon
    w = Label(wframe)
    w['image'] = self.m_icons['led_dark']
    w['justify'] = LEFT
    w.grid(row=row, column=col, sticky=W)
    d = {'val': False, 'var': None, 'w': w}
    self.m_robotStatus['estop_led'] = d

  #
  ## \brief Adjust status panel fields to fill width of joint state panel
  ##
  ## \param totWidth  Total text width of joint state panel
  #
  def adjustWidthRobotStatusPanel(self, totWidth):
    pass
    #width = (totWidth - 12) / 9
    #self.m_robotStatus['mode']['w']['width'] = 2 * width
    #self.m_robotStatus['calibration']['w']['width'] = 2 * width
    #self.m_robotStatus['motors']['w']['width'] = 2 * width
    #self.m_robotStatus['moving_label']['w']['width'] = width
    #self.m_robotStatus['alarms_label']['w']['width'] = width
    #self.m_robotStatus['estop_label']['w']['width'] = width

  #
  ## \brief Create joint state lower center panel headers.
  ##
  ## \param parent  Parent widget
  #
  def createWheelStatePanelHdr(self, parent):
    wframe = Frame(parent)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=0, padx=1, pady=3, sticky=N+W+E)
    self.m_wWheelStateFrame = wframe

    # heading
    w = Label(wframe)
    w['font'] =('Helvetica', 12)
    w['text'] = 'State'
    w['anchor'] = CENTER
    w.grid(row=0, column=0, columnspan=10, sticky=E+W)

    padx  = 10
    pady  = 3
    row   = 1

    self.m_icons['kuon_top_down'] = loadIcon("KuonTopDown300.png")

    w = Canvas(wframe, width=550, height=300)
    w.grid(row=row, column=0, columnspan=10, sticky=E+W)

    if self.m_icons['kuon_top_down'] is not None:
      w.create_image(270, 150, image=self.m_icons['kuon_top_down'])

    w.create_text(110,  50, text="N/A")
    w.create_text(110,  250, text="N/A")
    w.create_text(425, 50, text="N/A")
    w.create_text(425, 250, text="N/A")

  #
  ## \brief Create joint state lower center panel state.
  ##
  ## \param wheels Wheel state message.
  #
  def createWheelStatePanel(self, wheels):
    wframe = self.m_wWheelStateFrame
    width = 12
    
  #
  ## \brief Create gui right hand side buttons.
  #
  def createRightButtons(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=2, padx=1, pady=3, sticky=N+W+E)

    # estop
    w = self.createButton(wframe, "ESTOP", "icons/icon_estop.png", self.estop,
                                  fg='red')
    w.grid(row=0, column=0, sticky=N+E+W)
    self.m_icons['estop_reset'] = loadIcon("icons/icon_estop_reset.png")

    # clear alarms
    w = self.createButton(wframe, "Clear\nAlarms",
                                  "icons/icon_alarm.png", self.clearAlarms)
    w.grid(row=3, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('clear_alarms')

    # settings
    # RDK w = self.createButton(wframe, "Settings",
    # RDK                             "icons/icon_settings.png", self.settings)
    # RDK w.grid(row=4, column=0, sticky=N+E+W)

    # info
    w = self.createButton(wframe, "About",
                                  "icons/icon_info.png", self.about)
    w.grid(row=5, column=0, sticky=N+E+W)

    # quit
    w = self.createButton(wframe, "Quit", "icons/icon_exit.png", self.destroy,
                                  fg='red')
    w.grid(row=6, column=0, sticky=N+E+W)

  #
  ## \brief Create gui status bar at bottom of gui window.
  #
  def createStatusBar(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=2, column=0, columnspan=3, padx=1, pady=3, sticky=N+E+W+S)

    self.m_varStatus = StringVar()
    self.m_varStatus.set("")
    self.m_wStatusBar = Entry(wframe)
    self.m_wStatusBar['width']    = wframe['width']
    self.m_wStatusBar['relief']   = 'flat'
    self.m_wStatusBar['textvar']  = self.m_varStatus
    self.m_wStatusBar['fg']       = fgColors['normal']
    self.m_wStatusBar['state']    = 'readonly'
    self.m_wStatusBar.grid(row=0, column=0, padx=3, pady=3, sticky=N+E+W+S)

  #
  ## \brief Update button activation states.
  #
  def updateButtonState(self, keys, state):
    for key in keys:
      self.m_wBttn[key]['state'] = state

  #
  ## \brief Create button.
  ##
  ## \param parent    Parent widget.
  ## \param text      Button text.
  ## \param imagefile Image file name. None for no image.
  ## \param command   Callback for button push.
  ## \param fg        Foreground text color.
  ##
  ## \return Button widget.
  #
  def createButton(self, parent, text, imagefile, command, fg='black'):
    key = str.lower(text.replace("\n", "_"))
    self.m_icons[key] = loadIcon(imagefile)
    w = Button(parent)
    w['text']     = text
    if self.m_icons[key]:
      w['image']    = self.m_icons[key]
      w['compound'] = LEFT
      w['padx']     = 0
      w['pady']     = 0
      w['anchor']   = W
      w['width']    = 105
    else:
      w['anchor']   = CENTER
      w['width']    = 10
    w['fg']       = fg
    w['command']  = command
    self.m_wBttn[key] = w
    return self.m_wBttn[key]

  #
  ## \brief Destroy window callback.
  #
  def destroy(self):
    self.quit()

  #
  ## \brief Move forward
  #
  def kuonMoveForward(self):
    self.showInfo("Moving forward.")
    cmd = SpeedCmd()
    cmd.left  = 50;
    cmd.right = 50;
    self.m_pub_speed_cmd.publish(cmd)
  
  #
  ## \brief Move backward.
  #
  def kuonMoveBackward(self):
    self.showInfo("Moving back.")
    cmd = SpeedCmd()
    cmd.left  = -50;
    cmd.right = -50;
    self.m_pub_speed_cmd.publish(cmd)
  
  #
  ## \brief Spin left.
  #
  def kuonSpinLeft(self):
    self.showInfo("Spinning left.")
    cmd = SpeedCmd()
    cmd.left  = -50;
    cmd.right = 50;
    self.m_pub_speed_cmd.publish(cmd)
  
  #
  ## \brief Spin right.
  #
  def kuonSpinRight(self):
    self.showInfo("Spinning right.")
    cmd = SpeedCmd()
    cmd.left  = 50;
    cmd.right = -50;
    self.m_pub_speed_cmd.publish(cmd)
  
  #
  ## \brief Brake to stop.
  #
  def kuonStop(self):
    cmd = SpeedCmd()
    cmd.left  = 0;
    cmd.right = 0;
    self.m_pub_speed_cmd.publish(cmd)
    self.showInfo("Stopped.")
  
  #
  ## \brief Specify move callback.
  #
  def specifyMove(self):
    pass
    #jointTrajectory  = trajectory_msgs.msg.JointTrajectory()
    #jointTrajPoint   = trajectory_msgs.msg.JointTrajectoryPoint()  
    #jointTrajectory.points.append(jointTrajPoint)
    #for name,val in self.m_robotJoint.iteritems(): 
    #  jointTrajectory.joint_names.append(name)
    #  pos = self.m_robotJoint[name]['position']['var'].get()
    #  jointTrajPoint.positions.append(degToRad(pos))
    #  jointTrajPoint.velocities.append(10.0)
    #  jointTrajPoint.accelerations.append(0.0)
    #dlg = moveDlg(master=self, image='KuonInMotion.png',
    #                            trajectory=jointTrajectory)
    #if not dlg.m_result:
    #  return
    #else:
    #  self.cbMoveRobot(jointTrajectory)
  
  #
  ## \brief (Reset) emergency stop callback.
  #
  def estop(self):
    if not self.m_robotStatus['estop_led']['val']:
      self.showResetEStop()
      try:
        rospy.wait_for_service("kuon_control/estop", timeout=1)
      except rospy.ROSException, e:
        self.showError('Emergency stop: ' + e.message + '.')
        self.showEStop()
        return
      try:
        estop = rospy.ServiceProxy('kuon_control/estop', EStop)
        estop()
      except rospy.ServiceException, e:
        self.showError("Emergency stop request failed: %s." % (e.message))
        self.showEStop()
        return
      self.showError("Kuon emergency stopped.")
    else:
      self.showEStop()
      try:
        rospy.wait_for_service("kuon_control/reset_estop", timeout=1)
      except rospy.ROSException, e:
        self.showError('Reset emergency stop: ' + e.message + '.')
        self.showResetEStop()
        return
      try:
        reset_estop = rospy.ServiceProxy('kuon_control/reset_estop',
                                          ResetEStop)
        reset_estop()
      except rospy.ServiceException, e:
        self.showError("Reset emergency stop request failed: %s." % (e.message))
        self.showResetEStop()
        return
      self.showInfo("Kuon emergency stop has been reset.")
  
  #
  ## \brief Show estop button.
  #
  def showEStop(self):
    self.m_wBttn['estop']['image'] = self.m_icons['estop']
    self.m_wBttn['estop']['text']   = "ESTOP"
    self.m_wBttn['estop']['fg']     = fgColors['error']
    self.update_idletasks()

  #
  ## \brief Show reset estop button.
  #
  def showResetEStop(self):
    self.m_wBttn['estop']['image']  = self.m_icons['estop_reset']
    self.m_wBttn['estop']['text']   = "Reset\nESTOP"
    self.m_wBttn['estop']['fg']     = fgColors['normal']
    self.update_idletasks()

  #
  ## \brief Clear alarms callback.
  #
  def clearAlarms(self):
    try:
      rospy.wait_for_service("kuon_control/clear_alarms", timeout=1)
    except rospy.ROSException, e:
      self.showError('Clear alarms: ' + e.message + '.')
      return
    try:
      clear_alarms = rospy.ServiceProxy('kuon_control/clear_alarms',
                                          ClearAlarms)
      clear_alarms()
    except rospy.ServiceException, e:
      self.showError("Clear alarms request failed: %s." % (e.message))
      return
    self.showInfo("Alarms cleared.")
  
  #
  ## \brief Open settings dialog callback.
  #
  # RDK def settings(self):
  # RDK   dlg = configDlg(master=self, config=self.m_config)
  # RDK   self.m_config = dlg.m_config
  
  #
  ## \brief Show about dialog callback.
  #
  def about(self):
    prodInfo = None
    try:
      rospy.wait_for_service("kuon_control/get_product_info", timeout=1)
    except rospy.ROSException, e:
      self.showError('Get product info: ' + e.message + '.')
    else:
      try:
        get_product_info = rospy.ServiceProxy(
                                          'kuon_control/get_product_info',
                                          GetProductInfo)
        rsp = get_product_info()
        prodInfo = rsp.i
      except rospy.ServiceException, e:
        self.showError("Get product info request failed: %s." % (e.message))
    dlg = aboutDlg(master=self, info=prodInfo)
  
  #
  ## \brief Update robot status.
  ##
  ## \param status  Robot status extended message.
  #
  def updateRobotStatus(self, status):
    self.showRobotStatus(status)

  #
  ## \brief Update joint state.
  ##
  ## \param wheels Wheel state message.
  #
  def updateWheelStates(self, wheels):
    # no joints
    if len(joint.name) == 0:
      return

    # first state message, 
    if not self.m_bHasJointPanel:
      self.createWheelStatePanel(wheels)
    self.showWheelStates(wheels)

  #
  ## \brief Show robot status.
  ##
  ## \param status  Robot status extended message.
  #
  def showRobotStatus(self, status):
    if status.e_stopped:
      bNoMoves = True
    else:
      bNoMoves = False

    key = 'mode'
    if self.m_robotStatus[key]['val'] != status.mode:
      text, fg = self.toRobotMode(status.mode)
      self.m_robotStatus[key]['val'] = status.mode
      self.showEntry(self.m_robotStatus[key]['w'],
                     self.m_robotStatus[key]['var'], text, fg)
      if bNoMoves:
        state = 'disabled'
      else:
        state = 'normal'
      self.updateButtonState(self.m_keysNoMoves, state)

    key = 'motors'
    if self.m_robotStatus[key]['val'] != status.drives_powered:
      text, fg = self.toMotorsPowered(status.drives_powered)
      self.m_robotStatus[key]['val'] = status.drives_powered
      self.showEntry(self.m_robotStatus[key]['w'],
                     self.m_robotStatus[key]['var'], text, fg)

    key = 'moving_led'
    if self.m_robotStatus[key]['val'] != status.in_motion:
      self.m_robotStatus[key]['val'] = status.in_motion
      if status.in_motion:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_green'] 
      else:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_dark'] 

    key = 'alarms_led'
    if self.m_robotStatus[key]['val'] != status.in_error:
      self.m_robotStatus[key]['val'] = status.in_error
      if status.in_error:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_red'] 
      else:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_dark'] 

    key = 'estop_led'
    if self.m_robotStatus[key]['val'] != status.e_stopped:
      self.m_robotStatus[key]['val'] = status.e_stopped
      if status.e_stopped:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_red'] 
      else:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_dark'] 
      if bNoMoves:
        state = 'disabled'
      else:
        state = 'normal'
      self.updateButtonState(self.m_keysNoMoves, state)

  #
  ## \brief Show joint state.
  ##
  ## \param wheels Wheel state message.
  #
  def showWheelStates(self, wheels):
    pass
      #key = 'state'
      #val, fg = self.toWheelState(joint.op_state[i].calib_state)
      #if self.m_robotJoint[name][key]['var'].get() != val:
      #  self.showEntry(self.m_robotJoint[name][key]['w'],
      #               self.m_robotJoint[name][key]['var'], val, fg)


  #
  ## \brief Show servo health.
  ##
  ## \param health  Servo health message.
  #
  def showServoHealth(self, health):
    for i in range(0, len(health)):
      servo_id = health[i].servo_id
      if not self.m_robotServo.has_key(servo_id):
        continue

      name = self.m_robotServo[servo_id]

      key = 'temperature'
      val = int(health[i].temp)
      if self.m_robotJoint[name][key]['var'].get() != val:
        fg = self.toTemperatureColor(val)
        self.showEntry(self.m_robotJoint[name][key]['w'],
                       self.m_robotJoint[name][key]['var'], val, fg)

      key = 'voltage'
      val = health[i].voltage
      if self.m_robotJoint[name][key]['var'].get() != val:
        volts, fg = self.toVoltage(val)
        self.showEntry(self.m_robotJoint[name][key]['w'],
                       self.m_robotJoint[name][key]['var'], volts, fg)

      key = 'alarms'
      val, fg = self.toAlarms(health[i].alarm)
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                       self.m_robotJoint[name][key]['var'], val, fg)

  #
  ## \brief Show information message on status bar.
  ##
  ## \param msg   Info message string.
  #
  def showInfo(self, msg):
    self.m_wStatusBar["state"] = "normal"
    self.m_wStatusBar["fg"]    = fgColors['normal']
    self.m_varStatus.set(msg)
    self.m_wStatusBar["state"] = "readonly"

  #
  ## \brief Show error message on status bar.
  ##
  ## \param msg   Error message string.
  #
  def showError(self, msg):
    self.m_wStatusBar["state"] = "normal"
    self.m_wStatusBar["fg"]    = fgColors['error']
    self.m_varStatus.set(msg)
    self.m_wStatusBar["state"] = "readonly"

  #
  ## \brief Show text on read-only entry.
  ##
  ## \param w     Entry widget.
  ## \param var   Bound entry variable.
  ## \param val   Variable value.
  ## \param fg    Text foreground color.
  #
  def showEntry(self, w, var, val, fg='black'):
    w['state'] = 'normal'
    w['fg']    = fg
    var.set(val)
    w['state'] = 'readonly'

  def toRobotMode(self, mode):
    if mode:
      return ("Auto mode", fgColors['normal'])
    else:
      return ("Manual mode", fgColors['normal'])

  def toMotorsPowered(self, drives_powered):
    if drives_powered:
      return ("Motors powered", fgColors['normal'])
    else:
      return ("Motors unpowered", fgColors['normal'])

  def toWheelState(self, opstate):
      if opstate == KuonOpState.UNCALIBRATED:
        return ("uncalibrated", fgColors['error'])
      elif opstate == KuonOpState.CALIBRATING:
        return ("calibrating", fgColors['focus'])
      elif opstate == KuonOpState.CALIBRATED:
        return ("calibrated", fgColors['normal'])
      else:
        return (repr(opstate), fgColors['error'])

  def toDeg(self, rad):
    deg = math.degrees(rad)
    return round100th(deg), fgColors['normal']

  def toVelocity(self, percent):
    return round10th(percent), fgColors['normal']

  def toEffort(self, effort):
    absraw = math.fabs(effort)
    raw    = int(effort)
    if absraw < 900:
      return (raw, fgColors['normal'])
    elif absraw < 1000:
      return (raw, fgColors['warning'])
    else:
      return (raw, fgColors['error'])

  def toTemperatureColor(self, temp):
    if temp >= 75:
      return fgColors['error']
    elif temp >= 60:
      return fgColors['warning']
    else:
      return fgColors['normal']

  def toVoltage(self, volts):
    volts = round10th(volts)
    if volts >= 10.5 and volts <= 13.0:
      return (volts, fgColors['normal'])
    elif volts >= 9.5 and volts <= 13.5:
      return (volts, fgColors['warning'])
    else:
      return (volts, fgColors['error'])

  def toAlarms(self, alarms):
    if alarms == ServoHealth.ALARM_NONE:
      return (alarmStrings[ServoHealth.ALARM_NONE], fgColors['ok'])
    text = ""
    sep  = ""
    for bit in alarmStrings.keys():
      if bit & alarms:
        if len(alarmStrings[bit]) > 0:
          text += sep + alarmStrings[bit]
          sep = ','
    return (text, fgColors['error'])


# ------------------------------------------------------------------------------
# Exception Class usage
# ------------------------------------------------------------------------------

##
## \brief Unit test command-line exception class.
##
## Raise usage excpetion.
##
class usage(Exception):

  ##
  ## \brief Constructor.
  ##
  ## \param msg   Error message string.
  ##
  def __init__(self, msg):
    ## error message attribute
    self.msg = msg


# ------------------------------------------------------------------------------
# Class application
# ------------------------------------------------------------------------------

##
## \brief Kuon control panel.
##
class application():

  #
  ## \brief Constructor.
  #
  def __init__(self):
    self._Argv0 = __file__
    self.m_win = None

  #
  ## \brief Print usage error.
  ##
  ## \param emsg  Error message string.
  #
  def printUsageErr(self, emsg):
    if emsg:
      print "%s: %s" % (self._Argv0, emsg)
    else:
      print "%s: error" % (self._Argv0)
    print "Try '%s --help' for more information." % (self._Argv0)

  ## \brief Print Command-Line Usage Message.
  def printUsage(self):
    print \
"""
usage: %s [OPTIONS] <image_dir>

     %s --help

Options and arguments:

-h, --help                : Display this help and exit.
"""  % (self._Argv0, self._Argv0)
 
  #
  ## \brief Get command-line options
  ##  
  ## \param argv          Argument list. If not None, then overrides
  ##                      command-line arguments.
  ## \param [out] kwargs  Keyword argument list.  
  ##
  ## \return Parsed keyword arguments.
  #
  def getOptions(self, argv=None, **kwargs):
    if argv is None:
      argv = sys.argv

    self._Argv0 = kwargs.get('argv0', __file__)

    # defaults
    kwargs['debug'] = 0

    # parse command-line options
    try:
      opts, args = getopt.getopt(argv[1:], "?h",
          ['help', ''])
    except getopt.error, msg:
      raise usage(msg)
    for opt, optarg in opts:
      if opt in ('-h', '--help', '-?'):
        self.printUsage()
        sys.exit(0)

    #if len(args) < 1:
    #  self.printUsageErr("No input xml file specified")
    #  sys.exit(2)
    #else:
    #  kwargs['filename'] = args[0]

    return kwargs

  #
  ## \brief Initialize interface to kuon_robot.
  #
  def initRobot(self):
    self.m_win.showInfo("Initializing interface to Kuon.")

    rospy.init_node("kuon_panel")

    # subscribe to extended robot status data
    rospy.Subscriber("kuon_control/kuon_status", 
                     KuonStatus, 
                     self.updateRobotStatus) 

    # subscribe to extended joint state data
    rospy.Subscriber("kuon_control/kuon_state", 
                     KuonState, 
                     self.updateWheelStates) 

    self.m_win.showInfo("Kuon interface initialized.")

  #
  ## \brief Received robot extended status message callback.
  ##
  ## \param msg   Received message.
  #
  def updateRobotStatus(self, msg):
    self.m_win.updateRobotStatus(msg)

  #
  ## \brief Received joint extended state message callback.
  ##
  ## \param msg   Received message.
  #
  def updateWheelStates(self, msg):
    self.m_win.updateWheelStates(msg)

  #
  ## \brief Move robot along trajectory
  #
  def moveRobot(self, trajectory):
    try:
      self.m_joint_cmd_pub.publish(trajectory)
      self.m_win.showInfo('Move on specified trajectory.')
    except rospy.ROSException, e:
      self.m_win.showError('joint_command: ' + e.message + '.')

  #
  ## \brief Run application.
  ##    
  ## \param argv    Optional argument list to override command-line arguments.
  ## \param kwargs  Optional keyword argument list.
  ##
  ## \return Exit code.
  #
  def run(self, argv=None, **kwargs):
  
    # parse command-line options and arguments
    kwargs = self.getOptions(argv, **kwargs)

    # parse application configuration xml file
    filename = home + os.path.sep + kuonUserDirName + os.path.sep + \
        configFileName
    xml = configXml()
    config = xml.parse(filename)
    del xml

    # create root 
    root = Tk()

    # create application window
    self.m_win = window(master=root, config=config,
                                     pub_joint_move_cb=self.moveRobot)

    root.protocol('WM_DELETE_WINDOW', root.destroy)

    root.columnconfigure(0, weight=1)
    root.rowconfigure(0, weight=1)

    # initialize robot interface
    self.initRobot()

    # go for it
    self.m_win.mainloop()

    return 0


# ------------------------------------------------------------------------------
# main
# ------------------------------------------------------------------------------
if __name__ == '__main__':
  app = application();
  sys.exit( app.run() );
